name: Build and deploy main

 
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'porter.yaml'
      - 'Dockerfile.tmpl'
  workflow_dispatch:

jobs:
  porter-build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - name: Setup Porter
      uses: deislabs/porter-gh-action@v0.1.3

    - name: Pull in MChorfa's Helm3 mixin
      run: porter mixins install helm3 --url https://github.com/mchorfa/porter-helm3/releases/download --version v0.1.12

    - name: Login to GitHub Packages OCI Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PASSWORD }} # secrets.GHCR_PASSWORD
    - name: Retag bundle for ghcr.io
      run: |
        grep -oP -m 1 "(?<=version: )(\d.\d.\d)+" porter.yaml
        porter build --version "$(grep -oP -m 1 "(?<=version: )[0-9].[0-9].[0-9]+" porter.yaml)"-$(git rev-list --max-count=1 HEAD)
        # sed -i.bu 's/squillace/${{ github.repository_owner }}/g' ./porter.yaml
        # grep "registry:" ./porter.yaml
        # grep "version" ./porter.yaml
    - name: Porter publish to ghcr.io
      run: porter publish --registry ghcr.io/${{ github.repository_owner }}
